# Schema for the configuration file of newsletter module.

newsletter.settings:
  type: config_object
  label: 'Newsletter List Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content types Newsletter Form can display on'
      sequence:
        type: string
        label: 'Content type'
     