<?php

/**
 * @file
 * Layout Builder Quick Edit primary module file.
 */

use Drupal\block_content\BlockContentInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_load().
 */
function layout_builder_ibqe_entity_load(array $entities, $entity_type_id) {
  /** @var \Drupal\layout_builder_ibqe\BlockRevisionHelperInterface $helper */
  $helper = Drupal::service('layout_builder_ibqe.block_revision_helper');
  foreach ($entities as $entity) {
    if ($entity instanceof NodeInterface) {
      if ($entity->isPublished()) {
        continue;
      }
      if ($entity->hasField('layout_builder__layout') === FALSE) {
        continue;
      }

      $helper->updateBlockRevisionIds($entity);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function layout_builder_ibqe_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'quickedit_field_form') {
    $form['#validate'][] = 'layout_builder_ibqe_quick_edit_form_validate';
  }

}

/**
 * Implements hook_form_validate().
 */
function layout_builder_ibqe_quick_edit_form_validate(&$form, FormStateInterface $form_state) {
  $build_info = $form_state->getBuildInfo();
  if (isset($build_info['args'][0]) && $build_info['args'][0] instanceof BlockContentInterface) {
    /** @var \Drupal\block_content\BlockContentInterface $block_content */
    $block_content = $build_info['args'][0];
    /** @var \Drupal\layout_builder_ibqe\BlockRevisionHelperInterface $revision_helper */
    $revision_helper = \Drupal::service('layout_builder_ibqe.block_revision_helper');
    $needs_revision = $revision_helper->needsBlockNewRevision($block_content->id(), $block_content->getLoadedRevisionId());
    $block_content->setNewRevision($needs_revision);
  }
}
